version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: