services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '2610:2610'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: production
    command: yarn start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '2612:2612'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  calibrate:
      build:
        context: .
        dockerfile: ./apps/calibrate/Dockerfile
        target: production
      command: yarn start:dev calibrate
      env_file:
        - ./apps/calibrate/.env
      ports:
        - '2614:2614'
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules

  postgres:
      
      image: postgres
      env_file:
        - .env
      ports:
        - '5432:5432' 
      volumes:
        - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:            

