services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '2610:2610'
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '2612:2612'
    volumes:
      - .:/usr/src/app

  calibrate:
      build:
        context: .
        dockerfile: ./apps/calibrate/Dockerfile
        target: development
      command: yarn start:dev calibrate
      env_file:
        - ./apps/calibrate/.env
      ports:
        - '2614:2614'
      volumes:
        - .:/usr/src/app

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'